services:
  mongodb:
    image: mongo:latest
    ports:
      - "${DATABASE_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME:-cloak-service}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
